#Code Escape level layout override
#Tue May 12 14:43:32 IDT 2026
acceptedAnswers=
cells=0,0,0,0,0,0,0,0,0,0,0,0;0,0,0,0,0,0,0,0,0,0,0,0;0,0,0,0,0,0,0,0,0,0,0,0;0,0,0,0,0,0,0,0,0,0,0,0;0,0,0,0,0,0,0,0,0,0,0,0;0,0,0,0,0,0,0,0,0,0,0,0
chest.count=0
columns=12
goal.helper=Build\: System.out.println("Hello");
goal.instructions=Build a statement that prints "Hello".
goal.title=Printing
levelNumber=2
questionDoor.count=0
rows=6
token.0.chestOrder=0
token.0.column=3
token.0.kind=VISIBLE
token.0.row=0
token.0.type=CODE
token.0.value=System.out.println
token.1.chestOrder=0
token.1.column=2
token.1.kind=VISIBLE
token.1.row=4
token.1.type=CODE
token.1.value=(
token.2.chestOrder=0
token.2.column=6
token.2.kind=VISIBLE
token.2.row=3
token.2.type=CODE
token.2.value="Hello"
token.3.chestOrder=0
token.3.column=11
token.3.kind=VISIBLE
token.3.row=0
token.3.type=CODE
token.3.value=)
token.4.chestOrder=0
token.4.column=10
token.4.kind=VISIBLE
token.4.row=5
token.4.type=CODE
token.4.value=;
token.5.chestOrder=0
token.5.column=9
token.5.kind=VISIBLE
token.5.row=2
token.5.type=CODE
token.5.value=print
token.6.chestOrder=0
token.6.column=0
token.6.kind=VISIBLE
token.6.row=1
token.6.type=CODE
token.6.value="Hi"
token.count=7
tokens.overridden=true
version=1
