#Code Escape level layout override
#Tue May 12 14:48:56 IDT 2026
acceptedAnswers=
cells=0,0,0,0,0,0,0,0,0,0,0,0;0,0,0,0,0,0,0,0,0,0,0,0;0,0,0,0,0,0,0,0,0,0,0,0;0,0,0,0,0,0,0,0,0,0,0,0;0,0,0,0,0,0,0,0,0,0,0,0;0,0,0,0,0,0,0,0,0,0,0,0
chest.count=0
columns=12
goal.helper=Hint\: This solution has two statements\: declare score, then print score.
goal.instructions=Declare score as 10, then print score.
goal.title=Variable Output
levelNumber=3
questionDoor.count=0
rows=6
token.0.chestOrder=0
token.0.column=6
token.0.kind=VISIBLE
token.0.row=2
token.0.type=CODE
token.0.value=int
token.1.chestOrder=0
token.1.column=1
token.1.kind=VISIBLE
token.1.row=3
token.1.type=CODE
token.1.value=score
token.10.chestOrder=0
token.10.column=11
token.10.kind=VISIBLE
token.10.row=5
token.10.type=CODE
token.10.value=10.0
token.11.chestOrder=0
token.11.column=5
token.11.kind=VISIBLE
token.11.row=3
token.11.type=CODE
token.11.value=double
token.2.chestOrder=0
token.2.column=3
token.2.kind=VISIBLE
token.2.row=5
token.2.type=CODE
token.2.value=\=
token.3.chestOrder=0
token.3.column=5
token.3.kind=VISIBLE
token.3.row=0
token.3.type=CODE
token.3.value=10
token.4.chestOrder=0
token.4.column=7
token.4.kind=VISIBLE
token.4.row=0
token.4.type=CODE
token.4.value=;
token.5.chestOrder=0
token.5.column=9
token.5.kind=VISIBLE
token.5.row=0
token.5.type=CODE
token.5.value=System.out.println
token.6.chestOrder=0
token.6.column=0
token.6.kind=VISIBLE
token.6.row=1
token.6.type=CODE
token.6.value=(
token.7.chestOrder=0
token.7.column=2
token.7.kind=VISIBLE
token.7.row=1
token.7.type=CODE
token.7.value=score
token.8.chestOrder=0
token.8.column=0
token.8.kind=VISIBLE
token.8.row=5
token.8.type=CODE
token.8.value=)
token.9.chestOrder=0
token.9.column=5
token.9.kind=VISIBLE
token.9.row=5
token.9.type=CODE
token.9.value=;
token.count=12
tokens.overridden=true
version=1
