#Code Escape level layout override
#Saved game override for 2-2 - Logic Lock
acceptedAnswers=
cells=9,1,1,1,1,3,5,5,5,3,1,3;8,6,4,6,0,2,4,2,0,6,64,6;8,2,0,2,0,2,0,6,4,2,4,2;8,2,0,6,4,2,4,2,0,6,0,2;8,2,0,2,0,0,0,6,4,4,2,2;12,4,4,6,4,4,4,4,4,4,6,6
chest.0.column=0
chest.0.lockedRoomOnly=false
chest.0.row=1
chest.1.column=0
chest.1.lockedRoomOnly=false
chest.1.row=2
chest.10.column=4
chest.10.lockedRoomOnly=false
chest.10.row=2
chest.11.column=2
chest.11.lockedRoomOnly=false
chest.11.row=0
chest.12.column=3
chest.12.lockedRoomOnly=false
chest.12.row=2
chest.13.column=2
chest.13.lockedRoomOnly=false
chest.13.row=1
chest.2.column=11
chest.2.lockedRoomOnly=false
chest.2.row=0
chest.3.column=11
chest.3.lockedRoomOnly=false
chest.3.row=1
chest.4.column=8
chest.4.lockedRoomOnly=false
chest.4.row=0
chest.5.column=8
chest.5.lockedRoomOnly=false
chest.5.row=1
chest.6.column=6
chest.6.lockedRoomOnly=false
chest.6.row=0
chest.7.column=6
chest.7.lockedRoomOnly=false
chest.7.row=1
chest.8.column=4
chest.8.lockedRoomOnly=false
chest.8.row=0
chest.9.column=4
chest.9.lockedRoomOnly=false
chest.9.row=1
chest.count=14
columns=12
goal.helper=Hint: The solution uses two statements. Declare x first, then compare x.
goal.instructions=Declare a variable named x and then make a true if-statement using x.
goal.title=Variable and If
levelNumber=5
questionDoor.0.choices=boolean\u001fint\u001fclass\u001fString
questionDoor.0.code=____ flag = true; if (flag) {}
questionDoor.0.column=10
questionDoor.0.correctAnswer=boolean
questionDoor.0.prompt=Which type of variables can directly be used in an if-statement?
questionDoor.0.reward=true
questionDoor.0.row=1
questionDoor.0.side=BOTTOM
questionDoor.count=1
rows=6
token.0.chestOrder=0
token.0.column=0
token.0.kind=CHEST
token.0.row=0
token.0.type=CODE
token.0.value=;
token.1.chestOrder=1
token.1.column=0
token.1.kind=CHEST
token.1.row=0
token.1.type=CODE
token.1.value=x
token.10.chestOrder=10
token.10.column=0
token.10.kind=CHEST
token.10.row=0
token.10.type=CODE
token.10.value=\=
token.11.chestOrder=11
token.11.column=0
token.11.kind=CHEST
token.11.row=0
token.11.type=CODE
token.11.value=if
token.12.chestOrder=12
token.12.column=0
token.12.kind=CHEST
token.12.row=0
token.12.type=CODE
token.12.value=5
token.13.chestOrder=13
token.13.column=0
token.13.kind=CHEST
token.13.row=0
token.13.type=GOAL
token.13.value=Goal
token.2.chestOrder=2
token.2.column=0
token.2.kind=CHEST
token.2.row=0
token.2.type=CODE
token.2.value=(
token.3.chestOrder=3
token.3.column=0
token.3.kind=CHEST
token.3.row=0
token.3.type=CODE
token.3.value=)
token.4.chestOrder=4
token.4.column=0
token.4.kind=CHEST
token.4.row=0
token.4.type=CODE
token.4.value=int
token.5.chestOrder=5
token.5.column=0
token.5.kind=CHEST
token.5.row=0
token.5.type=CODE
token.5.value=x
token.6.chestOrder=6
token.6.column=0
token.6.kind=CHEST
token.6.row=0
token.6.type=CODE
token.6.value={
token.7.chestOrder=7
token.7.column=0
token.7.kind=CHEST
token.7.row=0
token.7.type=CODE
token.7.value=>
token.8.chestOrder=8
token.8.column=0
token.8.kind=CHEST
token.8.row=0
token.8.type=CODE
token.8.value=3
token.9.chestOrder=9
token.9.column=0
token.9.kind=CHEST
token.9.row=0
token.9.type=CODE
token.9.value=}
token.count=14
tokens.overridden=true
version=1
