#Code Escape level layout override
#Tue May 12 14:40:52 IDT 2026
acceptedAnswers=
cells=0,0,0,0,0,0,0,0,0,0,0,0;0,0,0,0,0,0,0,0,0,0,0,0;0,0,0,0,0,0,0,0,0,0,0,0;0,0,0,0,0,0,0,0,0,0,0,0;0,0,0,0,0,0,0,0,0,0,0,0;0,0,0,0,0,0,0,0,0,0,0,0
chest.count=0
columns=12
goal.helper=Build\: int x \= 5;
goal.instructions=Build a valid Java variable declaration.
goal.title=Variables
levelNumber=1
questionDoor.count=0
rows=6
token.0.chestOrder=0
token.0.column=0
token.0.kind=VISIBLE
token.0.row=0
token.0.type=CODE
token.0.value=int
token.1.chestOrder=0
token.1.column=2
token.1.kind=VISIBLE
token.1.row=0
token.1.type=CODE
token.1.value=x
token.2.chestOrder=0
token.2.column=4
token.2.kind=VISIBLE
token.2.row=0
token.2.type=CODE
token.2.value=\=
token.3.chestOrder=0
token.3.column=5
token.3.kind=VISIBLE
token.3.row=0
token.3.type=CODE
token.3.value=5
token.4.chestOrder=0
token.4.column=7
token.4.kind=VISIBLE
token.4.row=0
token.4.type=CODE
token.4.value=;
token.count=5
tokens.overridden=true
version=1
